# This is a basic workflow that is manually triggered

name: Create Commit

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  commit:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    # Checkout the branch
    - name: checkout
      uses: actions/checkout@v2

    - name: save current date
      run: date >> time.txt

    # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
    - name: setup git config
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"

    # Stage the file, commit and push
    - name: commit
      run: |
        git add time.txt
        git commit -m "new date commit"
        git push origin master
