# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Run ls
        run: ls -laGhF

      - name: Logging githug.event
        run: echo "${{toJSON(github.event)}}"

      - name: Logging githug.event.head_commit
        run: echo "${{toJSON(github.event.head_commit)}}"

      - name: Logging githug.event.pusher
        run: echo "${{toJSON(github.event.pusher)}}"

      - name: Echo pusher email
        run: echo "${{ github.event.pusher.email }}"

      - name: Echo commit message
        run: echo "${{ github.event.head_commit.message }}"

  versionning:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.genver.outputs.version }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0
    - name: Generate Version
      id: genver
      run: |
        VERSION=$(docker run --rm -v $(pwd):/repo codacy/git-version /bin/git-version --folder=/repo --release-branch=release --dev-branch=dev) 
        echo "::set-output name=version::$VERSION"
        echo $VERSION

  testAction:
    runs-on: ubuntu-latest
    name: A job to test local action - v${{ needs.versionning.outputs.version }}
    needs:
      - versionning
    steps:
      - uses: actions/checkout@v2
      - run: find .
      - uses: aneojgurhem/TestWorkflows@main
        id: foo
        with:
          who-to-greet: 'Mona the Octocat'
      - name: number - ${{ steps.foo.outputs.random-number }}
        run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash

  pushArtifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - run: echo hello > world.txt
      
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: world.txt

  htcMock:
    uses: aneoconsulting/ArmoniK/.github/workflows/test-mock.yml@JG/workflows
